### ISSUE TITLE
I-Sabre-K2M

### ISSUE THREAD

**Issue by antonellocaroli** [audiophonics/I-Sabre_9038Q2M#1]
I can't compile drivers on kernel 4.19...
I opened an issue here
https://github.com/SatoruKawase/I-Sabre-K2M/issues/5

but I don't have an answer...

**Comment by audiophonics** [comment]
You have it pre-compiled here for 4.19.25 : 
https://github.com/audiophonics/I-Sabre_9038Q2M_Compiled

The SatoruKawase version is deprecated above 4.17 version, our sources are updated
And they just has been integrated into kernel.

**Comment by antonellocaroli** [comment]
Yes, I did that version, too,

but only works in pcm, dsd dop does not emit sound...

**Comment by antonellocaroli** [comment]
`[/usr/sbin/networkaudiod] (1670): ALSA backend uninitialized
[/usr/sbin/networkaudiod] (1670): Set channels: 2 (2)
[/usr/sbin/networkaudiod] (1670): ALSA device: hw:CARD=DAC,DEV=0
[/usr/sbin/networkaudiod] (1670): ALSA access mode: RW_INTERLEAVED
[/usr/sbin/networkaudiod] (1670): ALSA PCM format: S32_LE
[/usr/sbin/networkaudiod] (1670): ALSA PCM bits: 32
[/usr/sbin/networkaudiod] (1670): ALSA PCM physical width: 32
[/usr/sbin/networkaudiod] (1670): ALSA PCM rates: 8000 - 384000
[/usr/sbin/networkaudiod] (1670): ALSA DSD not supported
[/usr/sbin/networkaudiod] (1670): ALSA rate available: 32000
[/usr/sbin/networkaudiod] (1670): ALSA rate available: 44100
[/usr/sbin/networkaudiod] (1670): ALSA rate available: 48000
[/usr/sbin/networkaudiod] (1670): ALSA rate available: 64000
[/usr/sbin/networkaudiod] (1670): ALSA rate available: 88200
[/usr/sbin/networkaudiod] (1670): ALSA rate available: 96000
[/usr/sbin/networkaudiod] (1670): ALSA rate available: 176400
[/usr/sbin/networkaudiod] (1670): ALSA rate available: 192000
[/usr/sbin/networkaudiod] (1670): ALSA rate available: 352800
[/usr/sbin/networkaudiod] (1670): ALSA rate available: 384000
[/usr/sbin/networkaudiod] (1670): ALSA backend initialized
[/usr/sbin/networkaudiod] (1670): ALSA PCM format available: 32000/32/2
[/usr/sbin/networkaudiod] (1670): ALSA PCM format available: 44100/32/2
[/usr/sbin/networkaudiod] (1670): ALSA PCM format available: 48000/32/2
[/usr/sbin/networkaudiod] (1670): ALSA PCM format available: 64000/32/2
[/usr/sbin/networkaudiod] (1670): ALSA PCM format available: 88200/32/2
[/usr/sbin/networkaudiod] (1670): ALSA PCM format available: 96000/32/2
[/usr/sbin/networkaudiod] (1670): ALSA PCM format available: 176400/32/2
[/usr/sbin/networkaudiod] (1670): ALSA PCM format available: 192000/32/2
[/usr/sbin/networkaudiod] (1670): ALSA PCM format available: 352800/32/2
[/usr/sbin/networkaudiod] (1670): ALSA PCM format available: 384000/32/2
`

ALSA DSD not supported

**Comment by audiophonics** [comment]
Which distribution and player are you using ?

**Comment by antonellocaroli** [comment]
as distribution use gentoo

the player is networkaudiod (endpoint of hqplayer)

but it's probably my dac that doesn't support dsd.
https://www.audiophonics.fr/fr/dac-et-interfaces-pour-raspberry-pi/st4000-dac-es9018k2m-hdmi-i2s-tcxo-32bit-384khz-pour-raspberry-pi-p-11848.html

anyway I saw that the driver is already included in the kernel...but to make it work anyway I have to follow the compilation...

Is it because I use a 64bit system or does it work like this in general?

**Comment by audiophonics** [comment]
You are right, this board can't play DSD, and our driver has no relation with this board, or any other ESS DAC board that are not I-Sabre 9028 or 9038 Q2M.
